version: 2
updates:

# GitHub actions
- package-ecosystem: github-actions
  directory: /
  commit-message:
    prefix: 'ci: TIO-84'
  schedule:
    interval: daily
    time: '01:00'
    timezone: Europe/Berlin
  open-pull-requests-limit: 10

# Flutter/Dart packages
- package-ecosystem: pub
  directory: /
  commit-message:
    prefix: 'chore: TIO-84'
  schedule:
    interval: daily
    time: '02:00'
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary

# Rust/Cargo
- package-ecosystem: cargo
  directory: /rust
  commit-message:
    prefix: 'chore: TIO-84'
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
