branches:
- name: main

tagFormat: v${version}

plugins:
-
  - '@semantic-release/commit-analyzer'
  - preset: angular
    releaseRules:
    - scope: no-release
      release: false
- '@semantic-release/release-notes-generator'
- '@semantic-release/github'
