extends: default

ignore-from-file: [.gitignore, .yamlignore]

rules:
  comments:
    level: error
  comments-indentation:
    level: error
  document-start: disable
  indentation:
    indent-sequences: false
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
    level: error
