# https://dart.dev/tools/linter-rules

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
  - lib/src/rust/**
  - lib/**.g.dart

formatter:
  line-length: 120

linter:
  rules:
#    always_declare_return_types: true
#    always_put_required_named_parameters_first: true
#    always_use_package_imports: true
#    avoid_annotating_with_dynamic: true
#    avoid_bool_literals_in_conditional_expressions: true
#    avoid_classes_with_only_static_members: true
    avoid_escaping_inner_quotes: true
#    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
#    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
#    avoid_slow_async_io: true
    avoid_type_to_string: true
#    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
#    avoid_void_async: true
    cancel_subscriptions: true
#    cascade_invocations: true
#    cast_nullable_to_non_nullable: true
    close_sinks: true
    combinators_ordering: true
    comment_references: true
    conditional_uri_does_not_exist: true
    deprecated_consistency: true
    deprecated_member_use_from_same_package: true
#    directives_ordering: true
#    discarded_futures: true
    do_not_use_environment: true
    document_ignores: true
    eol_at_end_of_file: true
    flutter_style_todos: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    literal_only_boolean_expressions: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_literal_bool_comparisons: true
    no_runtimetype_tostring: true
    no_self_assignments: true
    noop_primitive_operations: true
#    omit_local_variable_types: true
    one_member_abstracts: true
#    only_throw_errors: true
#    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
#    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
#    prefer_expression_function_bodies: true
#    prefer_final_in_for_each: true
#    prefer_final_locals: true
#    prefer_foreach: true
#    prefer_if_elements_to_conditional_expressions: true
#    prefer_int_literals: true
    prefer_mixin: true
#    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    prefer_void_to_null: true
#    require_trailing_commas: true
    sized_box_shrink_expand: true
#    sort_constructors_first: true
    sort_pub_dependencies: true
#    sort_unnamed_constructors_first: true
#    strict_top_level_inference: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
#    type_annotate_public_apis: true
#    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_library_directive: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_underscores: true
#    unreachable_from_main: true
#    use_colored_box: true
#    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
#    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
#    use_string_buffers: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    use_truncating_division: true
