# https://dart.dev/tools/linter-rules

linter:
  # TODO: enable the following rules
  rules:
    always_put_required_named_parameters_first: true
    avoid_dynamic_calls: false
    avoid_positional_boolean_parameters: false
    avoid_setters_without_getters: false
    constant_identifier_names: false
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: false # we prefer 120 chars
    no_default_cases: false
    one_member_abstracts: false
    prefer_function_declarations_over_variables: false
    public_member_api_docs: false
    type_annotate_public_apis: false

analyzer:
  # TODO: enable the following rules
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  exclude: [build/**, lib/src/rust/**.frb_generated.dart, lib/**.g.dart, rust/**, rust_builder/**]
