name: tiomusic
description: Home to your musical ideas.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: 3.9.0

dependencies:
  archive: 4.0.7
  audio_session: 0.2.2
  audioplayers: 6.5.1
  camera: 0.11.2
  circular_widgets: 3.0.0
  collection: 1.19.1
  equatable: 2.0.7
  ffi: 2.1.4
  file_picker: 10.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: 2.11.1
  flutter_svg: 2.2.1
  frontend_server_client: 4.0.0
  image_picker: 1.2.0
  image_picker_android: 0.8.13+1  # TODO: Delete when image_picker fixed limit for images on Android
  image_picker_platform_interface: 2.11.0  # TODO: Delete when image_picker fixed limit for images on Android
  intl: 0.20.2
  json_annotation: 4.9.0
  logger: 2.6.1
  meta: 1.16.0
  package_info_plus: 8.3.1
  path: 1.9.1
  path_provider: 2.1.5
  permission_handler: 12.0.1
  provider: 6.1.5+1
  rust_lib_tiomusic:
    path: rust_builder
  share_plus: 12.0.0
  tonic: 0.2.5
  tutorial_coach_mark: 1.3.1
  url_launcher: 6.3.2
  url_launcher_ios: 6.3.4
  uuid: 4.5.1
  volume_controller: 3.4.0
  wakelock_plus: 1.3.3
  wav: 1.5.0

dev_dependencies:
  build_runner: 2.10.0
  dependency_validator: 5.0.3
  ffigen: 19.1.0
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_native_splash: 2.4.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: 6.11.1
  mocktail: 1.0.4
  test_cov_console: 0.2.2

flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/
  - assets/metronome_sounds/
  - assets/midi_sounds/
  - assets/notes/
  - assets/rhythms/
  - assets/sound_fonts/
  - assets/splash/
  - assets/temp/sounds/
  - assets/themes/
