name: tiomusic
description: home to your musical ideas

publish_to: "none"

version: 0.0.1+1

environment:
    sdk: "3.7.0"

dependencies:
    archive: 4.0.7
    audio_session: 0.2.1
    audioplayers: 6.4.0
    camera: 0.11.1
    circular_widgets: 3.0.0
    collection: 1.19.1
    equatable: 2.0.7
    ffi: 2.1.3
    file_picker: 10.1.2
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    flutter_rust_bridge: 2.9.0
    flutter_svg: 2.1.0
    frontend_server_client: 4.0.0
    image_picker: 1.1.2
    intl: 0.19.0 # TODO: upgrade as soon as flutter_localizations supports it
    json_annotation: 4.9.0
    logger: 2.5.0
    meta: 1.16.0
    package_info_plus: 8.3.0
    path: 1.9.1
    path_provider: 2.1.5
    permission_handler: 12.0.0+1
    provider: 6.1.4
    rust_lib_tiomusic:
        path: rust_builder
    share_plus: 11.0.0
    stats: 2.1.0
    tonic: 0.2.5
    tutorial_coach_mark: 1.3.0
    url_launcher: 6.3.1
    url_launcher_ios: 6.3.3
    uuid: 4.5.1
    volume_controller: 3.3.3
    wakelock_plus: 1.3.2
    wav: 1.4.0

dev_dependencies:
    build_runner: 2.4.15
    dependency_validator: 4.1.2
    ffigen: 18.1.0
    flutter_launcher_icons: 0.14.3
    flutter_lints: 5.0.0
    flutter_native_splash: 2.4.6
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter
    json_serializable: 6.9.5
    mocktail: 1.0.4
    test_cov_console: 0.2.2

flutter:
    uses-material-design: true

    assets:
        - assets/icons/
        - assets/images/
        - assets/metronome_sounds/
        - assets/midi_sounds/
        - assets/notes/
        - assets/sound_fonts/
        - assets/splash/
        - assets/temp/sounds/
        - assets/themes/
