name: tiomusic
description: home to your musical ideas

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# this also needs to be changed in android/app/build.gradle for the android build to work
version: 1.0.8+91835875

environment:
    sdk: ">=3.6.1"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
    flutter:
        sdk: flutter

    ffi: 2.1.3
    meta: 1.15.0
    permission_handler: 11.3.1
    stats: 2.1.0
    path_provider: 2.1.5
    collection: 1.19.0
    provider: 6.1.2
    json_annotation: 4.9.0
    camera: 0.11.1
    path: 1.9.0
    image_picker: 1.1.2
    tonic: 0.2.5
    flutter_svg: 2.0.17
    intl: 0.20.2
    uuid: 4.5.1
    file_picker: 8.1.7
    wav: 1.3.0
    audioplayers: 6.1.0
    share_plus: 10.1.4
    url_launcher: 6.3.1
    url_launcher_ios: 6.3.2
    circular_widgets: 3.0.0
    audio_session: 0.1.24
    tutorial_coach_mark: 1.2.12
    wakelock_plus: 1.2.10
    equatable: 2.0.7
    rust_lib_tiomusic:
        path: rust_builder
    flutter_rust_bridge: 2.7.1
    archive: 4.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: 5.0.0
    ffigen: 16.1.0
    flutter_native_splash: 2.4.4
    flutter_launcher_icons: 0.14.3
    build_runner: 2.4.14
    json_serializable: 6.9.3
    dependency_validator: 4.1.1
    integration_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    assets:
        - assets/temp/sounds/
        - assets/icons/
        - assets/notes/
        - assets/midi_sounds/
        - assets/sound_fonts/
        - assets/metronome_sounds/
        - assets/themes/
        - assets/splash/
        - assets/images/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
