import 'package:tiomusic/domain/flash_cards/flash_card.dart';
import 'package:tiomusic/domain/flash_cards/category.dart';

final List<FlashCard> selfCareFlashCards = [
  FlashCard('selfCare001', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare001),
  FlashCard('selfCare002', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare002),
  FlashCard('selfCare003', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare003),
  FlashCard('selfCare004', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare004),
  FlashCard('selfCare005', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare005),
  FlashCard('selfCare006', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare006),
  FlashCard('selfCare007', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare007),
  FlashCard('selfCare008', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare008),
  FlashCard('selfCare009', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare009),
  FlashCard('selfCare010', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare010),
  FlashCard('selfCare011', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare011),
  FlashCard('selfCare012', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare012),
  FlashCard('selfCare013', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare013),
  FlashCard('selfCare014', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare014),
  FlashCard('selfCare015', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare015),
  FlashCard('selfCare016', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare016),
  FlashCard('selfCare017', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare017),
  FlashCard('selfCare018', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare018),
  FlashCard('selfCare019', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare019),
  FlashCard('selfCare020', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare020),
  FlashCard('selfCare021', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare021),
  FlashCard('selfCare022', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare022),
  FlashCard('selfCare023', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare023),
  FlashCard('selfCare024', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare024),
  FlashCard('selfCare025', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare025),
  FlashCard('selfCare026', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare026),
  FlashCard('selfCare027', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare027),
  FlashCard('selfCare028', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare028),
  FlashCard('selfCare029', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare029),
  FlashCard('selfCare030', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare030),
];
