import 'package:tiomusic/models/flash_cards.dart';
import 'package:tiomusic/domain/flash_cards/flash_cards_list_mix_up.dart';
import 'package:tiomusic/domain/flash_cards/flash_cards_list_practicing_tactics.dart';

final List<FlashCardModel> flashCards = [
  ...cultureFlashCards,
  ...journalingFlashCards,
  ...mixUpFlashCards,
  ...practicingTacticsFlashCards,
  ...relaxationFlashCards,
  ...selfCareFlashCards,
  ...teamFlashCards,
  ...visionFlashCards,
];

final List<FlashCardModel> cultureFlashCards = [
  FlashCardModel('culture001', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture001),
  FlashCardModel('culture002', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture002),
  FlashCardModel('culture003', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture003),
  FlashCardModel('culture004', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture004),
  FlashCardModel('culture005', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture005),
  FlashCardModel('culture006', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture006),
  FlashCardModel('culture007', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture007),
  FlashCardModel('culture008', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture008),
  FlashCardModel('culture009', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture009),
  FlashCardModel('culture010', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture010),
  FlashCardModel('culture011', FlashCardCategory.culture, (l10n) => l10n.descriptionCulture011),
];

final List<FlashCardModel> journalingFlashCards = [
  FlashCardModel('journaling001', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling001),
  FlashCardModel('journaling002', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling002),
  FlashCardModel('journaling003', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling003),
  FlashCardModel('journaling004', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling004),
  FlashCardModel('journaling005', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling005),
  FlashCardModel('journaling006', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling006),
  FlashCardModel('journaling007', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling007),
  FlashCardModel('journaling008', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling008),
  FlashCardModel('journaling009', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling009),
  FlashCardModel('journaling010', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling010),
  FlashCardModel('journaling011', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling011),
  FlashCardModel('journaling012', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling012),
  FlashCardModel('journaling013', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling013),
  FlashCardModel('journaling014', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling014),
  FlashCardModel('journaling015', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling015),
  FlashCardModel('journaling016', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling016),
  FlashCardModel('journaling017', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling017),
  FlashCardModel('journaling018', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling018),
  FlashCardModel('journaling019', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling019),
  FlashCardModel('journaling020', FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling020),
];

final List<FlashCardModel> relaxationFlashCards = [
  FlashCardModel('relaxation001', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation001),
  FlashCardModel('relaxation002', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation002),
  FlashCardModel('relaxation003', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation003),
  FlashCardModel('relaxation004', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation004),
  FlashCardModel('relaxation005', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation005),
  FlashCardModel('relaxation006', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation006),
  FlashCardModel('relaxation007', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation007),
  FlashCardModel('relaxation008', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation008),
  FlashCardModel('relaxation009', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation009),
  FlashCardModel('relaxation010', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation010),
  FlashCardModel('relaxation011', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation011),
  FlashCardModel('relaxation012', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation012),
  FlashCardModel('relaxation013', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation013),
  FlashCardModel('relaxation014', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation014),
  FlashCardModel('relaxation015', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation015),
  FlashCardModel('relaxation016', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation016),
  FlashCardModel('relaxation017', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation017),
  FlashCardModel('relaxation018', FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation018),
];

final List<FlashCardModel> selfCareFlashCards = [
  FlashCardModel('selfCare001', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare001),
  FlashCardModel('selfCare002', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare002),
  FlashCardModel('selfCare003', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare003),
  FlashCardModel('selfCare004', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare004),
  FlashCardModel('selfCare005', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare005),
  FlashCardModel('selfCare006', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare006),
  FlashCardModel('selfCare007', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare007),
  FlashCardModel('selfCare008', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare008),
  FlashCardModel('selfCare009', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare009),
  FlashCardModel('selfCare010', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare010),
  FlashCardModel('selfCare011', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare011),
  FlashCardModel('selfCare012', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare012),
  FlashCardModel('selfCare013', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare013),
  FlashCardModel('selfCare014', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare014),
  FlashCardModel('selfCare015', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare015),
  FlashCardModel('selfCare016', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare016),
  FlashCardModel('selfCare017', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare017),
  FlashCardModel('selfCare018', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare018),
  FlashCardModel('selfCare019', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare019),
  FlashCardModel('selfCare020', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare020),
  FlashCardModel('selfCare021', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare021),
  FlashCardModel('selfCare022', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare022),
  FlashCardModel('selfCare023', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare023),
  FlashCardModel('selfCare024', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare024),
  FlashCardModel('selfCare025', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare025),
  FlashCardModel('selfCare026', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare026),
  FlashCardModel('selfCare027', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare027),
  FlashCardModel('selfCare028', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare028),
  FlashCardModel('selfCare029', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare029),
  FlashCardModel('selfCare030', FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare030),
];

final List<FlashCardModel> teamFlashCards = [
  FlashCardModel('team001', FlashCardCategory.team, (l10n) => l10n.descriptionTeam001),
  FlashCardModel('team002', FlashCardCategory.team, (l10n) => l10n.descriptionTeam002),
  FlashCardModel('team003', FlashCardCategory.team, (l10n) => l10n.descriptionTeam003),
  FlashCardModel('team004', FlashCardCategory.team, (l10n) => l10n.descriptionTeam004),
  FlashCardModel('team005', FlashCardCategory.team, (l10n) => l10n.descriptionTeam005),
  FlashCardModel('team006', FlashCardCategory.team, (l10n) => l10n.descriptionTeam006),
  FlashCardModel('team007', FlashCardCategory.team, (l10n) => l10n.descriptionTeam007),
  FlashCardModel('team008', FlashCardCategory.team, (l10n) => l10n.descriptionTeam008),
  FlashCardModel('team009', FlashCardCategory.team, (l10n) => l10n.descriptionTeam009),
  FlashCardModel('team010', FlashCardCategory.team, (l10n) => l10n.descriptionTeam010),
  FlashCardModel('team011', FlashCardCategory.team, (l10n) => l10n.descriptionTeam011),
  FlashCardModel('team012', FlashCardCategory.team, (l10n) => l10n.descriptionTeam012),
  FlashCardModel('team013', FlashCardCategory.team, (l10n) => l10n.descriptionTeam013),
  FlashCardModel('team014', FlashCardCategory.team, (l10n) => l10n.descriptionTeam014),
  FlashCardModel('team015', FlashCardCategory.team, (l10n) => l10n.descriptionTeam015),
  FlashCardModel('team016', FlashCardCategory.team, (l10n) => l10n.descriptionTeam016),
  FlashCardModel('team017', FlashCardCategory.team, (l10n) => l10n.descriptionTeam017),
  FlashCardModel('team018', FlashCardCategory.team, (l10n) => l10n.descriptionTeam018),
];

final List<FlashCardModel> visionFlashCards = [
  FlashCardModel('vision001', FlashCardCategory.vision, (l10n) => l10n.descriptionVision001),
  FlashCardModel('vision002', FlashCardCategory.vision, (l10n) => l10n.descriptionVision002),
  FlashCardModel('vision003', FlashCardCategory.vision, (l10n) => l10n.descriptionVision003),
  FlashCardModel('vision004', FlashCardCategory.vision, (l10n) => l10n.descriptionVision004),
  FlashCardModel('vision005', FlashCardCategory.vision, (l10n) => l10n.descriptionVision005),
  FlashCardModel('vision006', FlashCardCategory.vision, (l10n) => l10n.descriptionVision006),
];
