import 'package:tiomusic/domain/flash_cards/flash_cards.dart';
import 'package:tiomusic/domain/flash_cards/flash_cards_list_mix_up.dart';
import 'package:tiomusic/domain/flash_cards/flash_cards_list_practicing_tactics.dart';

final List<FlashCardModel> flashCards = [
  ...cultureFlashCards,
  ...journalingFlashCards,
  ...mixUpFlashCards,
  ...practicingTacticsFlashCards,
  ...relaxationFlashCards,
  ...selfCareFlashCards,
  ...teamFlashCards,
  ...visionFlashCards,
];

final List<FlashCardModel> cultureFlashCards = [
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture001),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture002),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture003),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture004),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture005),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture006),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture007),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture008),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture009),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture010),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCulture011),
];

final List<FlashCardModel> journalingFlashCards = [
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling001),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling002),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling003),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling004),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling005),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling006),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling007),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling008),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling009),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling010),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling011),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling012),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling013),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling014),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling015),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling016),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling017),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling018),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling019),
  FlashCardModel((l) => l.categoryJournaling, (l) => l.descriptionJournaling020),
];

final List<FlashCardModel> relaxationFlashCards = [
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation001),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation002),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation003),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation004),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation005),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation006),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation007),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation008),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation009),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation010),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation011),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation012),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation013),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation014),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation015),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation016),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation017),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRelaxation018),
];

final List<FlashCardModel> selfCareFlashCards = [
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare001),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare002),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare003),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare004),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare005),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare006),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare007),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare008),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare009),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare010),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare011),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare012),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare013),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare014),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare015),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare016),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare017),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare018),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare019),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare020),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare021),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare022),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare023),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare024),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare025),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare026),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare027),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare028),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare029),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSelfCare030),
];

final List<FlashCardModel> teamFlashCards = [
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam001),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam002),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam003),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam004),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam005),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam006),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam007),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam008),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam009),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam010),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam011),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam012),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam013),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam014),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam015),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam016),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam017),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTeam018),
];

final List<FlashCardModel> visionFlashCards = [
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionVision001),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionVision002),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionVision003),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionVision004),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionVision005),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionVision006),
];
