import 'package:tiomusic/domain/flash_cards/flash_cards.dart';
import 'package:tiomusic/domain/flash_cards/flash_cards_list_mix_up.dart';
import 'package:tiomusic/domain/flash_cards/flash_cards_list_practicing_tactics.dart';

final List<FlashCardModel> flashCards = [
  ...cultureFlashCards,
  ...journalingFlashCards,
  ...mixUpFlashCards,
  ...practicingTacticsFlashCards,
  ...relaxationFlashCards,
  ...selfCareFlashCards,
  ...teamFlashCards,
  ...visionFlashCards,
];

final List<FlashCardModel> cultureFlashCards = [
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture001),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture002),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture003),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture004),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture005),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture006),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture007),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture008),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture009),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture010),
  FlashCardModel(FlashCardCategory.culture, (l10n) => l10n.descriptionCulture011),
];

final List<FlashCardModel> journalingFlashCards = [
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling001),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling002),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling003),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling004),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling005),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling006),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling007),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling008),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling009),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling010),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling011),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling012),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling013),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling014),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling015),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling016),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling017),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling018),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling019),
  FlashCardModel(FlashCardCategory.journaling, (l10n) => l10n.descriptionJournaling020),
];

final List<FlashCardModel> relaxationFlashCards = [
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation001),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation002),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation003),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation004),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation005),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation006),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation007),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation008),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation009),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation010),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation011),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation012),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation013),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation014),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation015),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation016),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation017),
  FlashCardModel(FlashCardCategory.relaxation, (l10n) => l10n.descriptionRelaxation018),
];

final List<FlashCardModel> selfCareFlashCards = [
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare001),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare002),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare003),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare004),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare005),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare006),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare007),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare008),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare009),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare010),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare011),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare012),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare013),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare014),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare015),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare016),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare017),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare018),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare019),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare020),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare021),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare022),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare023),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare024),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare025),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare026),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare027),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare028),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare029),
  FlashCardModel(FlashCardCategory.selfCare, (l10n) => l10n.descriptionSelfCare030),
];

final List<FlashCardModel> teamFlashCards = [
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam001),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam002),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam003),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam004),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam005),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam006),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam007),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam008),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam009),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam010),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam011),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam012),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam013),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam014),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam015),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam016),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam017),
  FlashCardModel(FlashCardCategory.team, (l10n) => l10n.descriptionTeam018),
];

final List<FlashCardModel> visionFlashCards = [
  FlashCardModel(FlashCardCategory.vision, (l10n) => l10n.descriptionVision001),
  FlashCardModel(FlashCardCategory.vision, (l10n) => l10n.descriptionVision002),
  FlashCardModel(FlashCardCategory.vision, (l10n) => l10n.descriptionVision003),
  FlashCardModel(FlashCardCategory.vision, (l10n) => l10n.descriptionVision004),
  FlashCardModel(FlashCardCategory.vision, (l10n) => l10n.descriptionVision005),
  FlashCardModel(FlashCardCategory.vision, (l10n) => l10n.descriptionVision006),
];
