import 'package:tiomusic/domain/flash_cards/flash_cards.dart';

List<FlashCardModel> flashCards = [
  // Relaxation additions
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionAllowNoAccomplishment),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionEyeExerciseDirections),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionEyeScanSixtySeconds),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionHumAndFeelSounds),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionListenFirstThenDecide),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionListenToBreathingThreeMinutes),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionPayAttentionHeartbeat),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionPayAttentionToBreathing),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRecordPhraseWatchMovements),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionRecordPlayingWatchFacialExpressions),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionReduceStressShakeStompLieDown),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionSitAndDoNothingFiveMinutes),
  FlashCardModel((l) => l.categoryRelaxation, (l) => l.descriptionSqueezeMusclesTenSeconds),

  // Team additions
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionAskDistractionWhilePlaying),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionAskFastForwardDuringPlayback),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionChatAboutAversionToPracticing),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionHandsOnShouldersReleaseTension),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionListenWithoutCommentFifteenMinutes),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionPlayChamberMusicTogether),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionPlayForSomeoneYouLike),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionPlayWithSomeone),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionPracticeWithFriend),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionSendVideoToFriend),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionSplitHandsOrPressKeysTogether),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionTellAFriendAndAskForTips),
  FlashCardModel((l) => l.categoryTeam, (l) => l.descriptionWatchSomeonePracticeWriteInspiration),

  // Self-Care additions
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionBiteIntoLemon),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionBodyPartsAwarenessList),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionBookForTonight),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionBookToHelpPractice),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionConsiderEffectivePracticeLocation),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionDrinkHalfLiterWater),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionEndWithFavoritePiece),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionExpressHowYouFeel),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionExpressWhatYouWantToGive),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionGingerShotOrRaw),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionGuidedMeditationBeforehand),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionHalfwayFiveMinuteBreak),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionMeetNeedsBeforeOrDuringBreaks),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionNoticeHeadIsFullTakeBreak),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionPlanDayOffInCalendar),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionPlanFinishWorkToday),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionPlanIdealBedtime),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionPracticeWithoutDevices),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionPrepareHoursBeforePerformance),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSeeHowYouCanHaveFun),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSleepInIfPossible),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionStartDayWithExercise),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionStartWithLongNotes),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionStartWithPhysicalExercises),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionSwitchToAirplaneMode),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionTenSecondBreakIfWorse),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionTidyRoomIfPossible),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionWalkWithoutDevices),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionWhichMealEnergizes),
  FlashCardModel((l) => l.categorySelfCare, (l) => l.descriptionWriteDownExtraneousThoughts),

  // Vision additions
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionLieDownUntilMotivated),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionMirrorMotivationalSpeech),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionPracticeWithGoalInMind),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionThinkWhyGetUpEarly),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionWriteDownDailyGoal),
  FlashCardModel((l) => l.categoryVision, (l) => l.descriptionWriteDownEuphoricMoments),

// Culture additions
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionBookConcertTicket),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionCreatePrivateConcert),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionDiscoverNewPieceInManyWays),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionListenToRoleModelAndLearn),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionPlanMeetFriendsListenMusic),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionReadBerliozTreatiseSection),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionReadWikipediaAboutInstrument),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionRediscoverPieceInManyWays),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionRewardYourself),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionWriteIntroForTwoTargetGroups),
  FlashCardModel((l) => l.categoryCulture, (l) => l.descriptionWriteTwoMinuteIntroduction),
];
