name: tiomusic_widgetbook
description: Widgetbook for TIO Music.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: 3.9.0

dependencies:
  accessibility_tools: 2.5.0
  flutter:
    sdk: flutter
  tiomusic:
    path: ../
  widgetbook: 3.14.2
  widgetbook_annotation: 3.5.0

dev_dependencies:
  build_runner: 2.4.15
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: 3.13.0

flutter:
  uses-material-design: true
