// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'float_index.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_interpolated`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `compute_rms`, `get_is_empty`, `get_is_looping`, `get_is_playing`, `get_length_seconds`, `get_playback_position_factor`, `get_samples`, `get_trim`, `new`, `set_loop`, `set_playback_position_factor`, `set_playing`, `set_trim`

class AudioBufferInterpolated {
  final double bufferSizeF32;
  final Float32List buffer;
  final bool looping;
  final bool isPlaying;
  final double startFactor;
  final double endFactor;
  final FloatIndex readHead;

  const AudioBufferInterpolated({
    required this.bufferSizeF32,
    required this.buffer,
    required this.looping,
    required this.isPlaying,
    required this.startFactor,
    required this.endFactor,
    required this.readHead,
  });

  @override
  int get hashCode =>
      bufferSizeF32.hashCode ^
      buffer.hashCode ^
      looping.hashCode ^
      isPlaying.hashCode ^
      startFactor.hashCode ^
      endFactor.hashCode ^
      readHead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioBufferInterpolated &&
          runtimeType == other.runtimeType &&
          bufferSizeF32 == other.bufferSizeF32 &&
          buffer == other.buffer &&
          looping == other.looping &&
          isPlaying == other.isPlaying &&
          startFactor == other.startFactor &&
          endFactor == other.endFactor &&
          readHead == other.readHead;
}
