// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_index`, `move_index`, `new`, `set_index`, `set_start_end`

class FloatIndex {
  final double start;
  final double end;
  final double index;
  final double range;

  const FloatIndex({required this.start, required this.end, required this.index, required this.range});

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ index.hashCode ^ range.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FloatIndex &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          index == other.index &&
          range == other.range;
}
