default_platform(:ios)

APPLE_APP_STORE_CONNECT_API_ISSUER_ID = ENV["APPLE_APP_STORE_CONNECT_API_ISSUER_ID"]
APPLE_APP_STORE_CONNECT_API_KEY_ID = ENV["APPLE_APP_STORE_CONNECT_API_KEY_ID"]
APPLE_APP_STORE_CONNECT_API_KEY_SECRET = ENV["APPLE_APP_STORE_CONNECT_API_KEY_SECRET"]

def api_key
  app_store_connect_api_key(
    key_id: APPLE_APP_STORE_CONNECT_API_KEY_ID,
    issuer_id: APPLE_APP_STORE_CONNECT_API_ISSUER_ID,
    key_content: APPLE_APP_STORE_CONNECT_API_KEY_SECRET,
    duration: 1200,
    in_house: false
  )
end

platform :ios do
  desc "Sign prod build"
  lane :get_certs_and_profiles do
      setup_ci()

      match(
        type: 'appstore',
        app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
        readonly: true,
      )
    end

  desc "Upload prod build to App Store"
  lane :push_to_store do
      changelog_from_git_commits()

      pilot(
        app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
        skip_waiting_for_build_processing: true,
        distribute_external: false,
        ipa: "../build/ios/ipa/TIO-Music.ipa",
        api_key: api_key()
      )
    end
end
