// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_event_time`, `get_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BeatEvent`, `MetroRhythmUnpacked`, `UpcomingEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from_usize`, `from_usize`, `from_usize`, `into_usize`, `into_usize`, `into_usize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_next_events`, `new`, `reset_playhead`

enum BeatSound {
  Accented,
  Accented2,
  Unaccented,
  Unaccented2,
  PolyAccented,
  PolyAccented2,
  PolyUnaccented,
  PolyUnaccented2,
  Muted,
}

enum BeatType { Accented, Unaccented, Muted }

enum BeatTypePoly { Accented, Unaccented, Muted }

class MetroBar {
  final int id;
  final List<BeatType> beats;
  final List<BeatTypePoly> polyBeats;
  final double beatLen;

  const MetroBar({
    required this.id,
    required this.beats,
    required this.polyBeats,
    required this.beatLen,
  });

  @override
  int get hashCode =>
      id.hashCode ^ beats.hashCode ^ polyBeats.hashCode ^ beatLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetroBar &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          beats == other.beats &&
          polyBeats == other.polyBeats &&
          beatLen == other.beatLen;
}
