name: PR – Verify title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Verify PR title
    runs-on: ubuntu-latest
    steps:
      - name: Assert PR title is semantic and includes JIRA ticket number
        uses: amannn/action-semantic-pull-request@v5.5.3
        with:
          subjectPattern: 'TIO-\d+: .+'
          subjectPatternError: >
            The PR title must include a JIRA ticket number in the format:
            "<type>[(<scope>)]: TIO-<#>: <description>"
            (example: fix(login): TIO-123: show error message on failed login attempt)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

