name: PR - Verify

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  verify:
    name: Verify
    uses: hfmnuernberg/TIO/.github/workflows/reusable-verify.yaml@main
    secrets: inherit
    with:
      ref: ${{ github.sha }}

  label-dependabot-pull-requests:
    name: Label Dependabot PRs by Semver
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Label PR by semver
        run: |
          scripts/label-pr-by-semver.sh \
            "${{ github.event.pull_request.title }}" \
            "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # see docs/dependabot.md
  auto-merge:
    name: Auto-merge
    needs: [verify, label-dependabot-pull-requests]
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: write
      deployments: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Print github.actor
        run: echo "${{ github.actor }}"

      - name: Print labels
        run: |
          echo "github.event.pull_request.labels: '${{ github.event.pull_request.labels }}'"
          echo "toJSON(github.event.pull_request.labels): '${{ toJSON(github.event.pull_request.labels) }}'"
          echo "contains(toJSON(github.event.pull_request.labels), 'semver: minor') '${{ contains(toJSON(github.event.pull_request.labels), 'semver: minor') }}'"
          echo "contains(toJSON(github.event.pull_request.labels), 'semver: patch') '${{ contains(toJSON(github.event.pull_request.labels), 'semver: patch') }}'"
          echo "$1 && ($2 || $3)'${{ github.actor == 'dependabot[bot]' && (contains(toJSON(github.event.pull_request.labels), 'semver: minor') || contains(toJSON(github.event.pull_request.labels), 'semver: patch')) }}'"

      - name: Enable auto-merge for Dependabot PRs (minor/patch only)
        if: >
          github.actor == 'dependabot[bot]' &&
          (
            contains(toJSON(github.event.pull_request.labels), 'semver: minor') ||
            contains(toJSON(github.event.pull_request.labels), 'semver: patch')
          )
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
