name: PR - Verify

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  verify:
    name: Verify
    uses: hfmnuernberg/TIO/.github/workflows/reusable-verify.yaml@main
    secrets: inherit
    with:
      ref: ${{ github.sha }}

  # see docs/dependabot.md
  auto-merge:
    name: Auto-merge
    needs: [verify]
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: write
      deployments: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Load semver from PR title
        id: semver
        run: |
          scripts/load-semver-from-pr-title.sh "${{ github.event.pull_request.title }}"
          echo "BUMP_TYPE=$BUMP_TYPE" >> "$GITHUB_OUTPUT"

      - name: Print actor
        run: |
          echo "actor: '${{ github.actor }}'"

      - name: Auto-merge if actor is Dependabot and bump is minor or patch
        if: >
          github.actor == 'dependabot[bot]' &&
          (steps.semver.outputs.BUMP_TYPE == 'minor' || steps.semver.outputs.BUMP_TYPE == 'patch')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
