name: PR - Label Dependabot PRs by Semver
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Label PR by semver
        run: |
          scripts/label-dependabot.sh \
            "${{ github.event.pull_request.title }}" \
            "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
