name: PR - Verify

on:
  pull_request:

jobs:
  verify:
    name: Verify
    uses: hfmnuernberg/TIO/.github/workflows/reusable-verify.yaml@main
    secrets: inherit
    with:
      ref: ${{ github.sha }}

  # see docs/dependabot.md
  auto-merge:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      contents: write
      deployments: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs (minor/patch only)
        if: >
          github.actor == 'dependabot[bot]' &&
          (
            contains(toJSON(github.event.pull_request.labels), 'semver: minor') ||
            contains(toJSON(github.event.pull_request.labels), 'semver: patch')
          )
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
