name: PR - Verify

on:
  pull_request:

jobs:
  verify:
    name: Verify
    uses: hfmnuernberg/TIO/.github/workflows/reusable-verify.yaml@TIO-21_coverage-threshold
    secrets: inherit
    with:
      ref: ${{ github.sha }}

  # see docs/dependabot.md
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4.2.2

      - name: Merge PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_PAT }}
