name: Bump Build Number

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
        description: The commit SHA, tag or release
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: The commit SHA, tag or release
    outputs:
      new_build_number:
        description: The new build number (e.g., 456)
        value: ${{ jobs.bump-build-number.outputs.new_build_number }}

permissions:
  contents: write

jobs:
  bump-build-number:
    name: Bump build number
    runs-on: ubuntu-latest
    outputs:
      new_build_number: ${{ steps.build_number.outputs.new_build_number }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0

    - name: Make scripts executable
      run: chmod +x scripts/*.sh

    - name: Configure Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - name: Bump build number
      id: build_number
      run: |
        source scripts/bump-build-number-and-tag.sh
        echo "old_build_number=$OLD_BUILD_NUMBER" >> "$GITHUB_OUTPUT"
        echo "new_build_number=$NEW_BUILD_NUMBER" >> "$GITHUB_OUTPUT"

    - name: Report build number
      run: |
        echo "Old Build Number: **${{ steps.build_number.outputs.old_build_number }}**" >> $GITHUB_STEP_SUMMARY
        echo "New Build Number: **${{ steps.build_number.outputs.new_build_number }}**" >> $GITHUB_STEP_SUMMARY
