name: Verify PR Title

on:
  workflow_dispatch:
    inputs:
      jira_key:
        required: true
        type: string
        description: The JIRA project key (usually 3-4 uppercase letters)
  workflow_call:
    inputs:
      jira_key:
        required: true
        type: string
        description: The JIRA project key (usually 3-4 uppercase letters)

jobs:
  verify-pr-title:
    name: Verify PR Title
    runs-on: ubuntu-latest
    steps:
    - name: Assert PR title is semantic and includes JIRA ticket number
      uses: amannn/action-semantic-pull-request@v5.5.3
      with:
        subjectPattern: '${{ inputs.jira_key }}-\d+: .+'
        subjectPatternError: >
          The PR title must include a JIRA ticket number in the format:
          "<type>[(<scope>)]: ${{ inputs.jira_key }}-<#>: <description>"
          (example: fix(login): ${{ inputs.jira_key }}-123: show error message on failed login attempt)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
