name: Test Xcode and macOS Version

on: [push, pull_request]

permissions:
  pull-requests: read

jobs:
  main:
    name: test Xcode and macOS version
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Check macOS version
        run: sw_vers

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Check macOS version
        run: sw_vers
