name: Test Xcode and macOS Version

on: [push, pull_request]

permissions:
  pull-requests: read

jobs:
  main:
    name: test Xcode and macOS version
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3.1

      - name: Install Flutter dependencies
        run: scripts/app.sh install:flutter:packages

      - name: Run Flutter doctor
        run: scripts/app.sh doctor

      - name: Check macOS version
        run: sw_vers

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Check macOS version
        run: sw_vers

      - name: Run Flutter doctor again
        run: scripts/app.sh doctor
